# The SSH options are passed verbatim to paramiko; see
# https://www.paramiko.org/ This is common CIJOE infrastructure
#
# Used by: cijoe.run() / cijoe.get() / cijoe.put()
[cijoe.transport.qemu_guest]
username = "root"
password = "root"
hostname = "localhost"
port = 4200

# Used by: the qemu.*.py scripts, adjust these if you are running a custom build
# of qemu, installed in a location not in PATH
[qemu]
system_bin = "qemu-system-x86_64"
img_bin = "qemu-img"

# Used by: qemu.guest_start.py and qemu.guest_kill.py
[qemu.guests.general-bios-x86_64]
system_bin = "qemu-system-x86_64"
path = "{{ local.env.HOME }}/guests/general-bios-x86_64"

# Keyword arguments: joined onto the form: "-cpu host -smp 4 -m 4" etc.
system_args.kwa = {cpu = "host", smp = 4, m = "6G", accel = "kvm"}

# Raw arguments: passed without modification to qemu-system-{arch}
system_args.raw = """\
-M "type=q35,kernel_irqchip=split" \
-device "intel-iommu,pt=on,intremap=on" \
"""

#
# Managed arguments: expands into longer incantations
#

# Uncomment this to 9p mount the given path with the guest
#system_args.host_share = "{{ local.env.HOME }}/git"

# Uncomment this to do a port-forward from host to guest, very convenient for
# e.g. SSH access to the guest
system_args.tcp_forward = {host = 4200, guest = 22}

# Used by:
#
# - system_imaging
# - qemu
#
# Thhe following is intended to be utilized a local collection of various
# system images, usable on base-metal, docker, and qemu-guests These can also be
# consumed by the
[system-imaging.images.alpine-x86_64]
cloud.url = "https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/cloud/nocloud_alpine-3.20.3-x86_64-bios-cloudinit-metal-r0.qcow2"
cloud.path = "{{ local.env.HOME }}/system_imaging/cloud/generic_alpine-3.20.3-x86_64-bios-cloudinit-metal-r0.qcow2"
cloud.metadata_path = "{{ resources.auxiliary['system_imaging.cloudinit-alpine-metadata'] }}"
cloud.userdata_path = "{{ resources.auxiliary['system_imaging.cloudinit-alpine-userdata-x86_64'] }}"

disk.url = "https://spdk-community-ci.s3.eu-central-003.backblazeb2.com/system/alpine-3.20-x86_64.qcow2"
disk.path = "{{ local.env.HOME }}/system_imaging/disk/alpine-x86_64.qcow2"

docker.url = "ghcr.io/refenv/alpine-3.20-x86_64:main"
docker.name = "alpine-3.20-x86_64"
docker.tag = "main"
