# The SSH options are passed verbatim to paramiko; see
# https://www.paramiko.org/ This is common CIJOE infrastructure
#
# Used by: cijoe.run() / cijoe.get() / cijoe.put()
[cijoe.transport.qemu_guest]
username = "root"
password = "root"
hostname = "localhost"
port = 4200

[cijoe.workflow]
fail_fast=true

# Used by: the qemu.*.py scripts
[qemu]
img_bin = "qemu-img"

[qemu.systems.aarch64]
bin = "qemu-system-aarch64"

[qemu.systems.x86_64]
bin = "qemu-system-x86_64"

# Used by: qemu.guest_initialize.py, qemu.guest_start.py, and qemu.guest_kill.py
[qemu.guests.generic-bios-kvm-x86_64]
path = "{{ local.env.HOME }}/guests/generic-bios-kvm-x86_64"

# Label of the qemu-system emulerator to use; see "qemu.systems"
system_label = "x86_64"

# Name of the system_image to use; see "system_imaging.images"
# Uncomment here, or set as workflow-argument when using "qemu.guest_initialize"
#system_image_name = "debian-12-x86_64"

# Keyword arguments: joined onto the form: "-cpu host -smp 4 -m 4" etc.
system_args.kwa = {cpu = "host", smp = 4, m = "6G", accel = "kvm"}

# Raw arguments: passed without modification to qemu-system-{arch}
system_args.raw = """\
-M "type=q35,kernel_irqchip=split" \
-device "intel-iommu,pt=on,intremap=on" \
"""

# TCP_FORWARD: Setup ssh forward from host to guest
#
# This is is a "special" argument, managed by the cijoe qemu-wrapper,
# specifically by 'guest.start_guest()'
system_args.tcp_forward = {host = 4200, guest = 22}

# HOST_SHARE: Sares the given folder with the guest via 9p
#
# The configuration example, below shares your home folder, if you do not want
# this, then comment it out
#
# This is is a "special" argument, managed by the cijoe qemu-wrapper,
# specifically by 'guest.start_guest()'
system_args.host_share = "{{ local.env.HOME }}"

[qemu.guests.generic-uefi-tcg-aarch64]
path = "{{ local.env.HOME }}/guests/generic-uefi-tcg-aarch64"

# Label of the qemu-system emulerator to use; see "qemu.systems"
system_label = "aarch64"

# Keyword arguments: joined onto the form: "-cpu host -smp 4 -m 4" etc.
system_args.kwa = {cpu = "max", smp = 4, m = "6G", accel = "tcg,thread=multi"}

# Raw arguments: passed without modification to qemu-system-{arch}
system_args.raw = """\
-M "virt,iommu=smmuv3,gic-version=3" \
"""

# INITIALIZE.DISKIMAGE: Options for the "qemu.guest_initialize" script
#
# You can uncomment it in your config here, or provide as argument as a workflow step-argument
#
#initialize.diskimage = "debian-12-aarch64"

# TCP_FORWARD: Setup ssh forward from host to guest
#
# This is is a "special" argument, managed by the cijoe qemu-wrapper,
# specifically by 'guest.start_guest()'
system_args.tcp_forward = {host = 4200, guest = 22}

# HOST_SHARE: Sares the given folder with the guest via 9p
#
# The configuration example, below shares your home folder, if you do not want
# this, then comment it out
#
# This is is a "special" argument, managed by the cijoe qemu-wrapper,
# specifically by 'guest.start_guest()'
system_args.host_share = "{{ local.env.HOME }}"

# SYSTEM_IMAGING: A collection of system images in the form of cloudimages,
# diskimages, and docker images.
#
#[system-imaging.images."alpine-3.21-x86_64"]
#system_label = "x86_64"

#cloud.url = "https://dl-cdn.alpinelinux.org/alpine/v3.21/releases/cloud/nocloud_alpine-3.21.0-x86_64-bios-cloudinit-metal-r0.qcow2"
#cloud.path = "{{ local.env.HOME }}/system_imaging/cloud/alpine-3.21-x86_64.qcow2"
#cloud.metadata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-metadata'] }}"
#cloud.userdata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-alpine-userdata'] }}"

#disk.path = "{{ local.env.HOME }}/system_imaging/disk/alpine-3.21-x86_64.qcow2"
#disk.url = "https://cijoe-system-imaging.s3.eu-central-003.backblazeb2.com/disk/alpine-3.21-x86_64.qcow2"
#disk.url_checksum = "https://cijoe-system-imaging.s3.eu-central-003.backblazeb2.com/disk/alpine-3.21-x86_64.qcow2.sha256"

#docker.url = "ghcr.io/refenv/alpine-3.21-x86_64:main"
#docker.name = "alpine-3.21-x86_64"
#docker.tag = "example"

[system-imaging.images.debian-12-x86_64]
system_label = "x86_64"

cloud.url = "https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-generic-amd64-daily.qcow2"
cloud.path = "{{ local.env.HOME }}/system_imaging/cloud/debian-12-generic-amd64-daily.qcow2"
cloud.metadata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-metadata'] }}"
cloud.userdata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-userdata'] }}"

disk.path = "{{ local.env.HOME }}/system_imaging/disk/debian-12-x86_64.qcow2"
disk.url = "https://cijoe-system-imaging.s3.eu-central-003.backblazeb2.com/disk/debian-12-x86_64.qcow2"
disk.url_checksum = "https://cijoe-system-imaging.s3.eu-central-003.backblazeb2.com/disk/debian-12-x86_64.qcow2"

docker.url = "ghcr.io/refenv/debian-12-x86_64:main"
docker.name = "debian-12-x86_64"
docker.tag = "example"

[system-imaging.images.fedora-41-x86_64]
system_label = "x86_64"

cloud.url ="https://download.fedoraproject.org/pub/fedora/linux/releases/41/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-41-1.4.x86_64.qcow2"
cloud.path = "{{ local.env.HOME }}/system_imaging/cloud/Fedora-Cloud-Base-Generic-41-1.4.x86_64.qcow2"
cloud.metadata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-metadata'] }}"
cloud.userdata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-userdata'] }}"

disk.path = "{{ local.env.HOME }}/system_imaging/disk/Fedora-Cloud-Base-Generic-41-1.4.x86_64.qcow2"

docker.url = "ghcr.io/refenv/fedora-41-x86_64:main"
docker.name = "fedora-41-x86_64"
docker.tag = "example"

[system-imaging.images.ubuntu-2404-x86_64]
system_label = "x86_64"

cloud.url = "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
cloud.path = "{{ local.env.HOME }}/system_imaging/cloud/noble-server-cloudimg-amd64.img"
cloud.metadata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-metadata'] }}"
cloud.userdata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-userdata'] }}"

disk.path = "{{ local.env.HOME }}/system_imaging/disk/noble-server-cloudimg-amd64.img"

docker.url = "ghcr.io/refenv/ubuntu-2404-x86_64:main"
docker.name = "ubuntu-2404-x86_64"
docker.tag = "example"

#[system-imaging.images.freebsd-x86_64]
#system_label = "x86_64"
#
#cloud.path = "{{ local.env.HOME }}/system_imaging/cloud/FreeBSD-14.2-RELEASE-amd64-BASIC-CLOUDINIT.ufs.qcow2"
#cloud.metadata_path = "{{ resources.auxiliary['system_imaging.cloudinit-freebsd-metadata'] }}"
#cloud.userdata_path = "{{ resources.auxiliary['system_imaging.cloudinit-freebsd-userdata'] }}"
#
#disk.path = "{{ local.env.HOME }}/system_imaging/disk/FreeBSD-14.2-RELEASE-amd64-BASIC-CLOUDINIT.ufs.qcow2"

[system-imaging.images.debian-12-aarch64]
system_label = "aarch64"

cloud.url = "https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-generic-arm64-daily.qcow2"
cloud.path = "{{ local.env.HOME }}/system_imaging/cloud/debian-12-generic-aarch64-daily.qcow2"
cloud.metadata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-metadata'] }}"
cloud.userdata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-userdata'] }}"

disk.path = "{{ local.env.HOME }}/system_imaging/disk/debian-12-aarch64.qcow2"

docker.url = "ghcr.io/refenv/debian-12-aarch64:main"
docker.name = "debian-12-aarch64"
docker.tag = "example"
