# The SSH options are passed verbatim to paramiko; see
# https://www.paramiko.org/ This is common CIJOE infrastructure
#
# Used by: cijoe.run() / cijoe.get() / cijoe.put()
[transport.ssh]
username = "root"
password = "root"
hostname = "localhost"
port = 4200

[os]
name = "debian"
version = "bookworm"

# Used by: qemu.build.py
[qemu.repository]
upstream = "https://github.com/qemu/qemu.git"
path = "{{ local.env.HOME }}/git/qemu"
tag = "v8.0.0"

# Used by: qemu.build.py
[qemu.build]
prefix = "{{ local.env.HOME }}/opt/qemu"

# Used by: the qemu.*.py scripts
[qemu]
#system_bin = "/opt/qemu/bin/qemu-system-x86_64"
system_bin = "{{ local.env.HOME }}/opt/qemu/bin/qemu-system-aarch64"
img_bin = "{{ local.env.HOME }}/opt/qemu/bin/qemu-img"
default_guest = "bookworm_arm64"

# Used by: qemu.guest_start.py and qemu.guest_kill.py
[qemu.guests.bookworm_arm64]
path = "{{ local.env.HOME }}/guests/debian-bookworm-arm64"

# Keyword arguments: joined onto the form: "-cpu host -smp 4 -m 4" etc.
system_args.kwa = {cpu = "host", smp = 4, m = "6G", accel = "hvf"}

# Raw arguments: passed without modification to qemu-system-{arch}
system_args.raw = """\
-M "virt,iommu=smmuv3,gic-version=3" \
-drive "file={{ local.env.HOME }}/opt/qemu/share/qemu/edk2-aarch64-code.fd,format=raw,if=pflash,readonly=on" \
"""

# Managed by qemu.guest_start.py, expands into longer system-arguments
system_args.tcp_forward = {host = 4200, guest = 22}
system_args.host_share = "{{ local.env.HOME }}/git"

# Used by: qemu.guest_init_using_bootimage.py
init_using_bootimage.url = "https://refenv.fra1.digitaloceanspaces.com/boot_images/debian-bookworm-arm64.qcow2"
init_using_bootimage.img = "{{ local.env.HOME }}/images/boot_images/debian-bookworm-arm64.qcow2"

# Used by: qemu.guest_init_using_cloudinit.py
init_using_cloudinit.url = "https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-generic-arm64-daily.qcow2"
init_using_cloudinit.img = "{{ local.env.HOME }}/images/cloudinit/debian-12-generic-arm64-daily.qcow2"
init_using_cloudinit.meta = "{{ resources.auxiliary['qemu.cloudinit-debian-meta'] }}"
init_using_cloudinit.user = "{{ resources.auxiliary['qemu.cloudinit-debian-user-arm64'] }}"
#init_using_cloudinit.pubkey = "keys/guest_key.pub"
