# The SSH options are passed verbatim to paramiko; see
# https://www.paramiko.org/ This is common CIJOE infrastructure
#
# Used by: cijoe.run() / cijoe.get() / cijoe.put()
[transport.ssh]
username = "root"
password = "root"
hostname = "localhost"
port = 4200

[os]
name = "debian"
version = "bullseye"

# Used by: qemu.build.py
[qemu.repository]
upstream = "https://github.com/qemu/qemu.git"
path = "{{ local.env.HOME }}/git/qemu"
tag = "v8.0.0"

# Used by: qemu.build.py
[qemu.build]
prefix = "{{ local.env.HOME }}/opt/qemu"

# Used by: the qemu.*.py scripts
[qemu]
#system_bin = "/opt/qemu/bin/qemu-system-x86_64"
system_bin = "{{ local.env.HOME }}/opt/qemu/bin/qemu-system-x86_64"
img_bin = "{{ local.env.HOME }}/opt/qemu/bin/qemu-img"
default_guest = "bullseye_amd64"

# Used by: qemu.guest_start.py and qemu.guest_kill.py
[qemu.guests.bullseye_amd64]
path = "{{ local.env.HOME }}/guests/debian-bullseye-amd64"

# Used by: qemu.guest_start.py (and qemu.guest_start_nvme.py)
system_args.kwa = {cpu = "host", smp = 4, m = "6G", accel = "kvm"}

# Raw arguments: passed without modification to qemu-system-{arch}
system_args.raw = """\
-M "type=q35,kernel_irqchip=split" \
-device "intel-iommu,pt=on,intremap=on" \
"""

# Managed by qemu.guest_start.py, expands into longer system-arguments
system_args.tcp_forward = {host = 4200, guest = 22}
system_args.host_share = "{{ local.env.HOME }}/git"

# Used by: qemu.guest_init_using_bootimage.py
init_using_bootimage.url = "https://refenv.fra1.digitaloceanspaces.com/boot_images/debian-bullseye-amd64.qcow2"
init_using_bootimage.img = "{{ local.env.HOME }}/images/boot_images/debian-bullseye-amd64.qcow2"

# Used by: qemu.guest_init_using_cloudinit.py
init_using_cloudinit.url = "https://cloud.debian.org/images/cloud/bullseye/daily/latest/debian-11-generic-amd64-daily.qcow2"
init_using_cloudinit.img = "{{ local.env.HOME }}/images/cloudinit/debian-11-generic-amd64-daily.qcow2"
init_using_cloudinit.meta = "{{ resources.auxiliary['qemu.cloudinit-debian-meta'] }}"
init_using_cloudinit.user = "{{ resources.auxiliary['qemu.cloudinit-debian-user-amd64'] }}"
#init_using_cloudinit.pubkey = "keys/guest_key.pub"
