# The SSH options are passed verbatim to paramiko; see
# https://www.paramiko.org/ This is common CIJOE infrastructure
#
# Used by: cijoe.run() / cijoe.get() / cijoe.put()
[cijoe.transport.ssh]
username = "root"
password = "root"
hostname = "localhost"
port = 4200

[os]
name = "debian"
version = "bookworm"

# Used by: qemu.build.py
[qemu.repository]
upstream = "https://github.com/qemu/qemu.git"
path = "{{ local.env.HOME }}/git/qemu"
tag = "v8.0.0"

# Used by: qemu.build.py
[qemu.build]
prefix = "{{ local.env.HOME }}/opt/qemu"

# Used by: the qemu.*.py scripts
[qemu]
#system_bin = "/opt/qemu/bin/qemu-system-x86_64"
system_bin = "{{ local.env.HOME }}/opt/qemu/bin/qemu-system-x86_64"
img_bin = "{{ local.env.HOME }}/opt/qemu/bin/qemu-img"
default_guest = "bookworm_amd64"

# Used by: qemu.guest_start.py and qemu.guest_kill.py
[qemu.guests.bookworm_amd64]
path = "{{ local.env.HOME }}/guests/debian-bookworm-amd64"

# Keyword arguments: joined onto the form: "-cpu host -smp 4 -m 4" etc.
system_args.kwa = {cpu = "host", smp = 4, m = "6G", accel = "kvm"}

# Raw arguments: passed without modification to qemu-system-{arch}
system_args.raw = """\
-M "type=q35,kernel_irqchip=split" \
-device "intel-iommu,pt=on,intremap=on" \
"""

# Managed arguments: expands into longer incantations
system_args.tcp_forward = {host = 4200, guest = 22}
system_args.host_share = "{{ local.env.HOME }}/git"

# Used by: qemu.guest_init_using_bootimage.py
init_using_bootimage.url = "https://refenv.fra1.digitaloceanspaces.com/boot_images/debian-bookworm-amd64.qcow2"
init_using_bootimage.img = "{{ local.env.HOME }}/images/boot_images/debian-bookworm-amd64.qcow2"

# Used by: qemu.guest_init_using_cloudinit
init_using_cloudinit.url = "https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-generic-amd64-daily.qcow2"
init_using_cloudinit.img = "{{ local.env.HOME }}/images/cloudinit/debian-12-generic-amd64-daily.qcow2"
init_using_cloudinit.meta = "{{ resources.auxiliary['qemu.cloudinit-debian-meta'] }}"
init_using_cloudinit.user = "{{ resources.auxiliary['qemu.cloudinit-debian-user-amd64'] }}"
#init_using_cloudinit.pubkey = "keys/guest_key.pub"
