# The SSH options are passed verbatim to paramiko; see
# https://www.paramiko.org/ This is common CIJOE infrastructure
#
# Used by: cijoe.run() / cijoe.get() / cijoe.put()

[cijoe.workflow]
fail_fast=true

# Used by: qemu.build.py
[qemu.repository]
remote = "https://github.com/qemu/qemu.git"
path = "{{ local.env.HOME }}/git/qemu"
tag = "v9.2.0"

# Used by: qemu.build.py
[qemu.build]
prefix = "{{ local.env.HOME }}/opt/qemu"

# Used by: the qemu.*.py scripts
[qemu]
system_bin = "{{ local.env.HOME }}/opt/qemu/bin/qemu-system-x86_64"
img_bin = "{{ local.env.HOME }}/opt/qemu/bin/qemu-img"
