## The SSH options are passed verbatim to paramiko; see
# https://www.paramiko.org/ This is common CIJOE infrastructure
#
# Used by: cijoe.run() / cijoe.get() / cijoe.put()
[cijoe.transport.qemu_guest]
username = "root"
password = "root"
hostname = "localhost"
port = 4200

[cijoe.workflow]
fail_fast=true

# Used by: the qemu.*.py scripts
[qemu]
img_bin = "qemu-img"

[qemu.systems.aarch64]
bin = "qemu-system-aarch64"

[qemu.systems.x86_64]
bin = "qemu-system-x86_64"

# Used by: qemu.guest_initialize.py, qemu.guest_start.py, and qemu.guest_kill.py
[qemu.guests.generic-uefi-tcg-aarch64]
path = "{{ local.env.HOME }}/guests/generic-uefi-tcg-aarch64"

# Label of the qemu-system emulerator to use; see "qemu.systems"
system_label = "aarch64"

# Keyword arguments: joined onto the form: "-cpu host -smp 4 -m 4" etc.
system_args.kwa = {cpu = "max", smp = 4, m = "6G", accel = "tcg,thread=multi"}

# Raw arguments: passed without modification to qemu-system-{arch}
system_args.raw = """\
-M "virt,iommu=smmuv3,gic-version=3" \
"""

# INITIALIZE.DISKIMAGE: Options for the "qemu.guest_initialize" script
#
# You can uncomment it in your config here, or provide as argument as a workflow step-argument
#
#initialize.diskimage = "debian-12-aarch64"

# TCP_FORWARD: Setup ssh forward from host to guest
#
# This is is a "special" argument, managed by the cijoe qemu-wrapper,
# specifically by 'guest.start_guest()'
system_args.tcp_forward = {host = 4200, guest = 22}

# HOST_SHARE: Sares the given folder with the guest via 9p
#
# The configuration example, below shares your home folder, if you do not want
# this, then comment it out
#
# This is is a "special" argument, managed by the cijoe qemu-wrapper,
# specifically by 'guest.start_guest()'
system_args.host_share = "{{ local.env.HOME }}"

# SYSTEM_IMAGING: A collection of system images in the form of cloudimages,
# diskimages, and docker images.
[system-imaging.images.debian-12-aarch64]
system_label = "aarch64"

cloud.url = "https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-generic-arm64-daily.qcow2"
cloud.path = "{{ local.env.HOME }}/system_imaging/cloud/debian-12-generic-aarch64-daily.qcow2"
cloud.metadata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-metadata'] }}"
cloud.userdata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-userdata'] }}"

disk.path = "{{ local.env.HOME }}/system_imaging/disk/debian-12-aarch64.qcow2"
disk.url = "https://refenv.fra1.digitaloceanspaces.com/boot_images/debian-bookworm-arm64.qcow2"
disk.url_checksum = "https://refenv.fra1.digitaloceanspaces.com/boot_images/debian-bookworm-arm64.qcow2.sha256"

docker.url = "ghcr.io/refenv/debian-12-aarch64:main"
docker.name = "debian-12-aarch64"
docker.tag = "example"
