## The SSH options are passed verbatim to paramiko; see
# https://www.paramiko.org/ This is common CIJOE infrastructure
#
# Used by: cijoe.run() / cijoe.get() / cijoe.put()
[cijoe.transport.qemu_guest]
username = "root"
password = "root"
hostname = "localhost"
port = 4200

[cijoe.workflow]
fail_fast=true

# Used by core.example_script_testrunner
[testrunner]
message = "Hello World!"

# Used by: the qemu.*.py scripts
[qemu]
img_bin = "qemu-img"

[qemu.systems.aarch64]
bin = "qemu-system-aarch64"

[qemu.systems.x86_64]
bin = "qemu-system-x86_64"

# Used by: qemu.guest_initialize.py, qemu.guest_start.py, and qemu.guest_kill.py
[qemu.guests.generic-bios-kvm-x86_64]
path = "{{ local.env.HOME }}/guests/generic-bios-kvm-x86_64"

# Label of the qemu-system emulerator to use; see "qemu.systems"
system_label = "x86_64"

# Name of the system_image to use; see "system_imaging.images"
# Uncomment here, or set as workflow-argument when using "qemu.guest_initialize"
#system_image_name = "debian-12-x86_64"

# Keyword arguments: joined onto the form: "-cpu host -smp 4 -m 4" etc.
system_args.kwa = {cpu = "host", smp = 4, m = "6G", accel = "kvm"}

# Raw arguments: passed without modification to qemu-system-{arch}
system_args.raw = """\
-M "type=q35,kernel_irqchip=split" \
-device "intel-iommu,pt=on,intremap=on" \
"""

# TCP_FORWARD: Setup ssh forward from host to guest
#
# This is is a "special" argument, managed by the cijoe qemu-wrapper,
# specifically by 'guest.start_guest()'
system_args.tcp_forward = {host = 4200, guest = 22}

# HOST_SHARE: Sares the given folder with the guest via 9p
#
# The configuration example, below shares your home folder, if you do not want
# this, then comment it out
#
# This is is a "special" argument, managed by the cijoe qemu-wrapper,
# specifically by 'guest.start_guest()'
system_args.host_share = "{{ local.env.HOME }}"
# SYSTEM_IMAGING: A collection of system images in the form of cloudimages,
# diskimages, and docker images.

[system-imaging.images.debian-12-x86_64]
system_label = "x86_64"

cloud.url = "https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-generic-amd64-daily.qcow2"
cloud.path = "{{ local.env.HOME }}/system_imaging/cloud/debian-12-generic-amd64-daily.qcow2"
cloud.metadata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-metadata'] }}"
cloud.userdata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-userdata'] }}"

disk.path = "{{ local.env.HOME }}/system_imaging/disk/debian-12-x86_64.qcow2"