# Used by: fio.{build,install,check} and by the wrapper for the location of the
# fio binary
[fio]
bin = "{{ local.env.HOME }}/opt/fio/bin/fio"

[fio.repository]
remote = "https://github.com/axboe/fio.git"
path = "{{ local.env.HOME }}/git/fio"

[fio.build]
prefix = "{{ local.env.HOME }}/opt/fio"
