# Declaration of where fio is located on the test-target and which IO-engines it
# has available
[fio]
bin = "{{ local.env.HOME }}/opt/fio/bin/fio"

[fio.engines.libaio]
type = "builtin"

[fio.engines.io_uring]
type = "builtin"

[fio.engines.io_uring_cmd]
type = "builtin"

[fio.engines.xnvme]
type = "builtin"

[fio.engines.spdk_nvme]
path = "/opt/aux/spdk_nvme"
type = "external_preload"

[fio.engines.spdk_bdev]
path = "/opt/aux/spdk_bdev"
type = "external_preload"
