---
name: cijoe_packages

on:
  pull_request:
  push:
    branches:
    - "main"
    tags:
    - "v*"

# This is needed for 'guestmount' / 'libguestfs'
env:
  LIBGUESTFS_BACKEND: direct

jobs:

  examples:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/refenv/cijoe-docker:latest
      options: --privileged

    strategy:
      fail-fast: false
      matrix:
        usage_example:
        - core.default
        - fio.default
        - linux.default
        - qemu.bootimage
        - qemu.build
        - qemu.cloudinit
        - system_imaging.default
        python-version: ['3.12']

    steps:
    - name: Grab source
      uses: actions/checkout@v4.2.2
      with:
        path: repository

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.3.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build and install cijoe from source
      run: |
        pipx uninstall cijoe
        cd repository
        make deps info build install
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Emit the example configuration file and workflow
      run: |
        cijoe --example ${{ matrix.usage_example }}

    - name: Run it!
      run: |
        cd cijoe-example-${{ matrix.usage_example }}
        cijoe --monitor -l

    - name: Upload report
      if: always()
      uses: actions/upload-artifact@v4.3.0
      with:
        name: report-cijoe_packages-${{ matrix.usage_example }}
        path: cijoe-example-${{ matrix.usage_example }}/cijoe-output/*
        if-no-files-found: error
